### ISSUE TITLE
Can not load on maya 2022.1

### ISSUE THREAD

**Issue by camel259** [daz3d/DazToMaya#10]
Only errors due loading

**Comment by Popinjayishuman** [comment]
Could you give us some more information please? We would like to help you with your issue.

**Comment by DryreL** [comment]
How to access/run DazToMaya bridge in Maya 2022? It's not in the Plugin Manager

**Comment by camel259** [comment]
> Could you give us some more information please? We would like to help you with your issue.
Hello.
Old version of plugin works in 2018 and 2020, when is putted to ..\My_Documents\maya\plug-ins
New version in  ..\My_Documents\maya\2022\modules or in Maya's program directory don't works at all.
There is no plugin in Manager to load.

**Comment by DryreL** [comment]
Hi. Thanks for the fast answer. It seems you switched plugins to modules. I installed modules into my documents 'maya' but I didn't understand how to access Daz3D in Maya 2022.

**Comment by camel259** [comment]
@DryreL:
Not me - I'm only Maya user :>

@Popinjayishuman is the plugin creator.

**Comment by DryreL** [comment]
Ah so! Actually you answered the question yourself :D

There is no plugins folder in this new version. They switched "modules" folder. It auto-loads to shelves itself.

![image](https://user-images.githubusercontent.com/20909077/131992859-9b53374c-880a-4c4d-9f80-c2bd29920669.png)

As you can see, I was looking for this and found it, thanks to you.

![image](https://user-images.githubusercontent.com/20909077/131992938-085cb3cf-2127-401b-a1c5-21ea25f5dc85.png)

**Comment by camel259** [comment]
@DryreL  Ouh, yeees. It's working :>
Thanx a lot, bro.

I've rewritten script which is loading module in 2022 or plugin in Maya 2020 or lower

#starting here
import maya.cmds as cmds
if int(cmds.about(v=True)) > 2020:
	import sys
	sys.dont_write_bytecode = True  # don't write PYCs
	import DazToMaya
	import importlib
	importlib.reload(DazToMaya)
	reload(DazToMaya)
	DazToMaya.run()
else:
	mel.eval('loadPlugin -quiet DazToMaya')
	mel.eval('daztomaya')

cmds.inViewMessage( amg='<hl>Daz To Maya</hl> Loaded', pos='topCenter', fade=True )
sys.stdout.write('Daz To Maya Loaded.\n')

**Comment by DryreL** [comment]
Nice to hear that!

**Comment by Popinjayishuman** [comment]
Hey there guys, glad to see you figured this out yourselves but so everyone is clear, the bridge is no longer a plugin but a module inside Maya.

**Comment by stepharamburu** [comment]
doesn't work for me. Still telling me "Nothing to Import", I'll never understand how a company as DAZ can release an unuseful update.
