### ISSUE TITLE
DazToMaya Bridge Can't Load Maya 2018

### ISSUE THREAD

**Issue by sureshrkumar** [daz3d/DazToMaya#13]
Issue no:01

Note:
I'm Downloaded 'Master' Githup file 

1. I'm Mac User and Maya 2018 version. Dazstudios "DazToMaya Bridge' Script was working. But Maya Plug-in manager 'Daztomaya' Plug-ins tick on and showing error // Warning: file: /Applications/Autodesk/maya2018/Maya.app/Contents/scripts/others/pluginWin.mel line 290: No initializePlugin() or initializePlugin2() function
 // 
// Error: file: /Applications/Autodesk/maya2018/Maya.app/Contents/scripts/others/pluginWin.mel line 290:  (DazToMaya) //

Issue no:2

Note:
I'm Downloaded 'DazToMaya 1.6'  Githup file 

2.DazToMaya.py Script are working but DazToMaya Import tab can't visable.

@samjay3d  @Popinjayishuman 
Please help me how to resolve this

**Comment by Popinjayishuman** [comment]
The bridge does not activate as a plugin anymore and is now a script which will be found on the toolbar. You can safely uninstall the plugin version.

**Comment by sureshrkumar** [comment]
> The bridge does not activate as a plugin anymore and is now a script which will be found on the toolbar. You can safely uninstall the plugin versio

> The bridge does not activate as a plugin anymore and is now a script which will be found on the toolbar. You can safely uninstall the plugin version.
