### ISSUE TITLE
Import into Maya takes 30+ minutes

### ISSUE THREAD

**Issue by mostlyhuman** [daz3d/DazToMaya#3]
I have so much content that it takes a very long time (about 35 minutes on my decently fast laptop) to import a single figure into Maya with the plugin because there are hundreds of morphs that the plugin force-exports.  Can you possibly make it where it uses the last-used morph export rules from the fbx exporter so these can be more easily controlled with .csv morph lists? This would also help for general morph export customization in addition to fixing the forced expression exports. Also, the long import into Maya is a little bit faster on my desktop but not by much.

**Comment by mostlyhuman** [comment]
Any word on this? Still an issue. It is still taking half an hour to import a character since it force saves all of the facial expressions in my library to the FBX file.  I am assuming this was not tested with larger DAZ libraries.  We need some way to control what gets exported.  Just for reference I have an AMD 3070x CPU with 128GB of ram and a Samsung 980 Pro hard drive and it still takes 30 minutes to import into Maya because of all the unneeded morphs/blendshapes. Thanks in advance for any consideration!

**Comment by Popinjayishuman** [comment]
Sorry for such a long response time, we now have more support for the maya bridge and now have a response team available. The current version of the bridge supports choosing individual morphs. If you update and have any further issues feel free to open a new issue and we should be much quicker on the draw. Thank you for understanding!
