### ISSUE TITLE
Plugin load error in Maya 2022 + Mac OSX Catalina

### ISSUE THREAD

**Issue by indefinit** [daz3d/DazToMaya#4]
Hi there,

I keep getting the following error in Maya when I try to load the DazToMaya plugin. It seems to happen in both version 1.6 and 1.7 (master branch). I'm running Mac OSX Catalina and Maya 2022. 

```
Error: file: /Applications/Autodesk/maya2022/Maya.app/Contents/scripts/others/pluginWin.mel line 316:  (DazToMaya) // 
```

I'm not sure why it's trying to load pluginWin when I'm running Maya on a Mac. Any help is much appreciated!

**Comment by guto88** [comment]
I have the same issue on Windows and Maya 2022

**Comment by guto88** [comment]
I just submitted a pull request with this plugin updated to Python 3. I'm using this version without any issues with Maya 2022.

**Comment by Popinjayishuman** [comment]
The current version of the bridge on the daz store has support maya 2022.
