### ISSUE TITLE
Daz3d Textures to Arnold issues

### ISSUE THREAD

**Issue by pholland1** [daz3d/DazToMaya#54]
![daz capture1](https://github.com/daz3d/DazToMaya/assets/112729423/e7f12abf-b5ce-4ced-927e-bbdb527f74e9)
![rendercaratest01](https://github.com/daz3d/DazToMaya/assets/112729423/4722faae-d82e-46a1-b622-563acbcfbdf1)
![rendercaratest02](https://github.com/daz3d/DazToMaya/assets/112729423/8388b16c-6759-43fc-a34c-fd6545fa4fc4)

so I have been trying to work with daz3d models in maya for a month or so and world like some help with the textures please. 

wither keeping the textures as is or converting them to arnold textures i get poor results when rendering a final image. this character (CB Cara) is a extreme example of this. attatch are to images, the first is what the character looks like when rendering her in daz3d and the send is a render in my. 

I might be asking for to much for a one-to-one conversion. And I really appreciate the bridge as i love the daz models. I just need so advice as to fix things on my end. As a 3d animator i only know the basics of texturing and rendering shots. so any help and or advice would be amazing. 

cheers

**Comment by pholland1** [comment]
> Here are some tips for using DazToMaya with Arnold Renderer:
> 
> 1. Make sure your character's materials are all using the "PBRSkin" or the "Iray Uber" shader in the Surfaces tab of Daz Studio.
> 2. After importing you character using "Auto-Import", click "Convert Materials" with "Arnold" selected from the dropdown.
> 3. Make sure you only use Arnold-specific lighting for your scene: in the main menu, click Arnold -> Lights -> Physical Sky.
> 
> Tutorials for Maya Arnold: https://help.autodesk.com/view/ARNOL/ENU/?guid=arnold_for_maya_tutorials_am_Introduction_to_Arnold_for_Maya_html https://www.youtube.com/watch?v=twq3yohtrSE https://www.youtube.com/watch?v=sp_TTSAe2nE

Thank you for replying to my question.

I have been doing steps 2 and 3 but have never gone into Daz3d's own Surfacing tab to alter anything before. I do not know where to see if the "PBRSkin" or "Iray Uber" shaders are on or not. I tried to search the terms in the search bar and it did not come up with anything for either of the terms. 

Edit: i just noticed below the "editor" tab it reads; Shader; Iray Uber (MDL) when i select Genesis 8.1 female eyelashes and tear. when selecting the model it reads "<Multiple>"

can you please go further into what i should be looking for? how do I change these things to what you recommend?

**Comment by danielbui78** [comment]
Here is an introduction to materials and shaders in Daz Studio: https://youtu.be/Jb_c7NJtrek
If you have further questions on working with Daz Studio materials and shaders, the Daz Forums are a very good resource.

In general, most Genesis 8, 8.1 and 9 characters sold on the Daz Store will have a material set based on Iray Uber or PBRSkin shaders for the character's skin.  Hair and clothing assets, however, may use materials based on custom shaders.  You may be able to build an Iray Uber compatible material using the source textures from these non-IrayUber materials.

There are some paid products which can convert materials based on 3Delight shaders to Iray Uber, but those are mainly relevant to Genesis 3 and below.

**Comment by pholland1** [comment]
thanks for the help :)
