### ISSUE TITLE
new update not working in maya 2020

### ISSUE THREAD

**Issue by Peter2089** [daz3d/DazToMaya#7]
Hi there seems to be an update 2 days ago of the plugin, which made the plugin no longer active in maya 2020.
It doesn't even appear in the Plugin Manager.
I try to install it manually from github but it doesn't work either.

**Comment by vatlu** [comment]
The new version of the Maya plugin should now be available under the shelf "DazToMaya". 

![image](https://user-images.githubusercontent.com/68863061/128301080-ea1f7ddf-18c4-4d73-acb1-9ebb460a0ba8.png)
